name: Version Bump

on:
  pull_request:
    branches:
      - dev
    types:
      - closed
jobs:
  bump:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: bump
        run: |
          python bump_version.py --file_path apps/app/build.gradle --type 'build'

      - name: commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add history.txt
          git commit -m "Bump version"
          git push origin dev