name: Version Bump

on:
  pull_request:
    branches:
      - dev
    types:
      - closed
jobs:
  bump:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: bump
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ $BRANCH_NAME == "feat"* ]]; then
            echo "Bump version for feature branch" >> history.txt
          elif [[ $BRANCH_NAME == "fix"* ]]; then
            echo "Bump version for fix branch" >> history.txt
          else
            echo "Bump version for unknown branch" >> history.txt
          fi

      - name: commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add history.txt
          git commit -m "Bump version"
          git push origin dev